<?php

declare(strict_types=1);

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Driver\Selector;
use SebastianBergmann\CodeCoverage\Filter;
use SebastianBergmann\CodeCoverage\Report\PHP as PhpReport;

$filter_ = new Filter();

$filter_->includeFiles(
    [
        __DIR__ . '/about.php',
        __DIR__ . '/action.php',
        __DIR__ . '/admin.php',
        __DIR__ . '/admin/album.php',
        __DIR__ . '/admin/album_notification.php',
        __DIR__ . '/admin/albums.php',
        __DIR__ . '/admin/batch_manager.php',
        __DIR__ . '/admin/batch_manager_global.php',
        __DIR__ . '/admin/batch_manager_unit.php',
        __DIR__ . '/admin/cat_list.php',
        __DIR__ . '/admin/cat_modify.php',
        __DIR__ . '/admin/cat_options.php',
        __DIR__ . '/admin/cat_perm.php',
        __DIR__ . '/admin/cat_search.php',
        __DIR__ . '/admin/comments.php',
        __DIR__ . '/admin/configuration.php',
        __DIR__ . '/admin/element_set_ranks.php',
        __DIR__ . '/admin/extend_for_templates.php',
        __DIR__ . '/admin/group_list.php',
        __DIR__ . '/admin/group_perm.php',
        __DIR__ . '/admin/help.php',
        __DIR__ . '/admin/history.php',
        __DIR__ . '/admin/inc/add_core_tabs.inc.php',
        __DIR__ . '/admin/inc/albums_tab.inc.php',
        __DIR__ . '/admin/inc/c13y_internal.class.php',
        __DIR__ . '/admin/inc/check_integrity.class.php',
        __DIR__ . '/admin/inc/configuration_sizes_process.inc.php',
        __DIR__ . '/admin/inc/configuration_watermark_process.inc.php',
        __DIR__ . '/admin/inc/functions.php',
        __DIR__ . '/admin/inc/functions_history.inc.php',
        __DIR__ . '/admin/inc/functions_install.inc.php',
        __DIR__ . '/admin/inc/functions_metadata.php',
        __DIR__ . '/admin/inc/functions_notification_by_mail.inc.php',
        __DIR__ . '/admin/inc/functions_permalinks.php',
        __DIR__ . '/admin/inc/functions_plugins.inc.php',
        __DIR__ . '/admin/inc/functions_upgrade.php',
        __DIR__ . '/admin/inc/functions_upload.inc.php',
        __DIR__ . '/admin/inc/image.class.php',
        __DIR__ . '/admin/inc/index.php',
        __DIR__ . '/admin/inc/languages.class.php',
        __DIR__ . '/admin/inc/photos_add_direct_prepare.inc.php',
        __DIR__ . '/admin/inc/plugins.class.php',
        __DIR__ . '/admin/inc/tabsheet.class.php',
        __DIR__ . '/admin/inc/themes.class.php',
        __DIR__ . '/admin/inc/updates.class.php',
        __DIR__ . '/admin/inc/user_tabs.inc.php',
        __DIR__ . '/admin/index.php',
        __DIR__ . '/admin/intro.php',
        __DIR__ . '/admin/languages.php',
        __DIR__ . '/admin/languages_installed.php',
        __DIR__ . '/admin/languages_new.php',
        __DIR__ . '/admin/maintenance.php',
        __DIR__ . '/admin/maintenance_actions.php',
        __DIR__ . '/admin/maintenance_env.php',
        __DIR__ . '/admin/menubar.php',
        __DIR__ . '/admin/notification_by_mail.php',
        __DIR__ . '/admin/permalinks.php',
        __DIR__ . '/admin/photo.php',
        __DIR__ . '/admin/photos_add.php',
        __DIR__ . '/admin/photos_add_applications.php',
        __DIR__ . '/admin/photos_add_direct.php',
        __DIR__ . '/admin/photos_add_ftp.php',
        __DIR__ . '/admin/picture_coi.php',
        __DIR__ . '/admin/picture_formats.php',
        __DIR__ . '/admin/picture_modify.php',
        __DIR__ . '/admin/plugin.php',
        __DIR__ . '/admin/plugins.php',
        __DIR__ . '/admin/plugins_installed.php',
        __DIR__ . '/admin/plugins_new.php',
        __DIR__ . '/admin/popuphelp.php',
        __DIR__ . '/admin/profile.php',
        __DIR__ . '/admin/rating.php',
        __DIR__ . '/admin/rating_user.php',
        __DIR__ . '/admin/site_manager.php',
        __DIR__ . '/admin/site_reader_local.php',
        __DIR__ . '/admin/site_update.php',
        __DIR__ . '/admin/stats.php',
        __DIR__ . '/admin/tags.php',
        __DIR__ . '/admin/theme.php',
        __DIR__ . '/admin/themes.php',
        __DIR__ . '/admin/themes_installed.php',
        __DIR__ . '/admin/themes_new.php',
        __DIR__ . '/admin/updates.php',
        __DIR__ . '/admin/updates_ext.php',
        __DIR__ . '/admin/updates_pwg.php',
        __DIR__ . '/admin/user_activity.php',
        __DIR__ . '/admin/user_list.php',
        __DIR__ . '/admin/user_perm.php',
        __DIR__ . '/comments.php',
        __DIR__ . '/doc/index.php',
        __DIR__ . '/ecs.php',
        __DIR__ . '/feed.php',
        __DIR__ . '/galleries/index.php',
        __DIR__ . '/i.php',
        __DIR__ . '/identification.php',
        __DIR__ . '/inc/block.class.php',
        __DIR__ . '/inc/cache.class.php',
        __DIR__ . '/inc/calendar_base.class.php',
        __DIR__ . '/inc/calendar_monthly.class.php',
        __DIR__ . '/inc/calendar_weekly.class.php',
        __DIR__ . '/inc/category_cats.inc.php',
        __DIR__ . '/inc/category_default.inc.php',
        __DIR__ . '/inc/common.inc.php',
        __DIR__ . '/inc/config_default.inc.php',
        __DIR__ . '/inc/constants.php',
        __DIR__ . '/inc/dblayer/functions_mysqli.inc.php',
        __DIR__ . '/inc/derivative.inc.php',
        __DIR__ . '/inc/derivative_params.inc.php',
        __DIR__ . '/inc/derivative_std_params.inc.php',
        __DIR__ . '/inc/filter.inc.php',
        __DIR__ . '/inc/functions.inc.php',
        __DIR__ . '/inc/functions_calendar.inc.php',
        __DIR__ . '/inc/functions_category.inc.php',
        __DIR__ . '/inc/functions_comment.inc.php',
        __DIR__ . '/inc/functions_cookie.inc.php',
        __DIR__ . '/inc/functions_filter.inc.php',
        __DIR__ . '/inc/functions_html.inc.php',
        __DIR__ . '/inc/functions_mail.inc.php',
        __DIR__ . '/inc/functions_metadata.inc.php',
        __DIR__ . '/inc/functions_notification.inc.php',
        __DIR__ . '/inc/functions_picture.inc.php',
        __DIR__ . '/inc/functions_plugins.inc.php',
        __DIR__ . '/inc/functions_rate.inc.php',
        __DIR__ . '/inc/functions_search.inc.php',
        __DIR__ . '/inc/functions_session.inc.php',
        __DIR__ . '/inc/functions_tag.inc.php',
        __DIR__ . '/inc/functions_url.inc.php',
        __DIR__ . '/inc/functions_user.inc.php',
        __DIR__ . '/inc/index.php',
        __DIR__ . '/inc/inflectors/en.php',
        __DIR__ . '/inc/inflectors/fr.php',
        __DIR__ . '/inc/menubar.inc.php',
        __DIR__ . '/inc/no_photo_yet.inc.php',
        __DIR__ . '/inc/page_header.php',
        __DIR__ . '/inc/page_tail.php',
        __DIR__ . '/inc/picture_comment.inc.php',
        __DIR__ . '/inc/picture_metadata.inc.php',
        __DIR__ . '/inc/picture_rate.inc.php',
        __DIR__ . '/inc/section_init.inc.php',
        __DIR__ . '/inc/template.class.php',
        __DIR__ . '/inc/user.inc.php',
        __DIR__ . '/inc/ws_core.inc.php',
        __DIR__ . '/inc/ws_functions.inc.php',
        __DIR__ . '/inc/ws_functions/index.php',
        __DIR__ . '/inc/ws_functions/pwg.categories.php',
        __DIR__ . '/inc/ws_functions/pwg.extensions.php',
        __DIR__ . '/inc/ws_functions/pwg.groups.php',
        __DIR__ . '/inc/ws_functions/pwg.images.php',
        __DIR__ . '/inc/ws_functions/pwg.permissions.php',
        __DIR__ . '/inc/ws_functions/pwg.php',
        __DIR__ . '/inc/ws_functions/pwg.tags.php',
        __DIR__ . '/inc/ws_functions/pwg.users.php',
        __DIR__ . '/inc/ws_init.inc.php',
        __DIR__ . '/inc/ws_protocols/index.php',
        __DIR__ . '/inc/ws_protocols/json_encoder.php',
        __DIR__ . '/inc/ws_protocols/php_encoder.php',
        __DIR__ . '/inc/ws_protocols/rest_encoder.php',
        __DIR__ . '/inc/ws_protocols/rest_handler.php',
        __DIR__ . '/inc/ws_protocols/xmlrpc_encoder.php',
        __DIR__ . '/index.php',
        __DIR__ . '/install.php',
        __DIR__ . '/install/index.php',
        __DIR__ . '/nbm.php',
        __DIR__ . '/notification.php',
        __DIR__ . '/password.php',
        __DIR__ . '/picture.php',
        __DIR__ . '/plugins/AdminTools/admin.php',
        __DIR__ . '/plugins/AdminTools/index.php',
        __DIR__ . '/plugins/AdminTools/main.inc.php',
        __DIR__ . '/plugins/AdminTools/maintain.class.php',
        __DIR__ . '/plugins/GDThumb/admin.php',
        __DIR__ . '/plugins/GDThumb/changelog.php',
        __DIR__ . '/plugins/GDThumb/config_default.inc.php',
        __DIR__ . '/plugins/GDThumb/index.php',
        __DIR__ . '/plugins/GDThumb/main.inc.php',
        __DIR__ . '/plugins/GDThumb/maintain.class.php',
        __DIR__ . '/plugins/index.php',
        __DIR__ . '/plugins/language_switch/index.php',
        __DIR__ . '/plugins/language_switch/language_switch.inc.php',
        __DIR__ . '/plugins/language_switch/main.inc.php',
        __DIR__ . '/plugins/LocalFilesEditor/admin.php',
        __DIR__ . '/plugins/LocalFilesEditor/index.php',
        __DIR__ . '/plugins/LocalFilesEditor/main.inc.php',
        __DIR__ . '/plugins/LocalFilesEditor/maintain.inc.php',
        __DIR__ . '/plugins/LocalFilesEditor/show_default.php',
        __DIR__ . '/plugins/rv_tscroller/main.inc.php',
        __DIR__ . '/plugins/TakeATour/admin.php',
        __DIR__ . '/plugins/TakeATour/main.inc.php',
        __DIR__ . '/popuphelp.php',
        __DIR__ . '/profile.php',
        __DIR__ . '/qsearch.php',
        __DIR__ . '/random.php',
        __DIR__ . '/rector.php',
        __DIR__ . '/register.php',
        __DIR__ . '/search.php',
        __DIR__ . '/search_rules.php',
        __DIR__ . '/tags.php',
        __DIR__ . '/template-extension/index.php',
        __DIR__ . '/template-extension/yoga/index.php',
        __DIR__ . '/themes/bootstrap_darkroom/index.php',
        __DIR__ . '/themes/bootstrap_darkroom/themeconf.inc.php',
        __DIR__ . '/themes/default/index.php',
        __DIR__ . '/themes/default/themeconf.inc.php',
        __DIR__ . '/themes/elegant/index.php',
        __DIR__ . '/themes/elegant/themeconf.inc.php',
        __DIR__ . '/themes/index.php',
        __DIR__ . '/themes/modus/functions.inc.php',
        __DIR__ . '/themes/modus/index.php',
        __DIR__ . '/themes/modus/themeconf.inc.php',
        __DIR__ . '/themes/smartpocket/themeconf.inc.php',
        __DIR__ . '/upgrade.php',
        __DIR__ . '/upgrade_feed.php',
        __DIR__ . '/ws.php',
    ]
);

$coverage_ = new CodeCoverage(
    (new Selector())->forLineCoverage($filter_),
    $filter_
);
$coverage_->excludeUncoveredFiles();

$coverage_->start($_SERVER['REQUEST_URI']);

function save_coverage(): void
{
    global $coverage_;
    $coverage_->stop();
    (new PhpReport())->process($coverage_, 'C:/Apache24/logs/xdebug/coverage/' . bin2hex(random_bytes(16)) . '.cov');
}

register_shutdown_function('save_coverage');
